import os
import networkx as nx

class DocGenerator:
    """
    Generates markdown documentation from the analyzed graph.
    """
    def __init__(self, analyzer, llm_interface=None):
        self.analyzer = analyzer
        self.llm = llm_interface

    def generate_map(self, project_path: str) -> str:
        graph = self.analyzer.get_graph()
        metadata = self.analyzer.file_metadata
        output_path = os.path.join(project_path, "PROJECT_MAP.md")
        
        lines = []
        lines.append(f"# Project Map: {os.path.basename(project_path)}")
        lines.append(f"**Generated by Code_Navigator**\n")
        lines.append(f"- **Files Processed**: {len(metadata)}")
        lines.append(f"- **Total Nodes**: {graph.number_of_nodes()}\n")
        
        lines.append("## 1. High-Level Architecture")
        # Identify "Hubs" (files with many incoming edges)
        degrees = sorted(graph.in_degree, key=lambda x: x[1], reverse=True)
        lines.append("| File | Incoming Dependents |")
        lines.append("|---|---|")
        for node, degree in degrees[:5]:
            if node in metadata:
                lines.append(f"| `{node}` | {degree} |")
        lines.append("\n")

        lines.append("## 2. File Details")
        
        # Sort files alphabetically
        sorted_files = sorted(metadata.keys())
        
        for rel_path in sorted_files:
            data = metadata[rel_path]
            lines.append(f"### 📄 `{rel_path}`")
            
            # Dependencies
            out_edges = graph.successors(rel_path)
            deps = [n for n in out_edges if not n.startswith(rel_path)] # Filter internal symbols
            if deps:
                clean_deps = [d.replace("LIB:", "External: ") for d in deps]
                lines.append(f"**Dependencies:** `{', '.join(clean_deps)}`\n")
            
            # Definitions Table
            if data['definitions']:
                lines.append("| Type | Name |")
                lines.append("|---|---|")
                for d in data['definitions']:
                    lines.append(f"| {d.type} | `{d.name}` |")
            else:
                lines.append("*No top-level definitions found.*")
            
            lines.append("\n---\n")
            
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
            
        return output_path